# netlify.toml
[build]
  command = "echo 'No build required'"
  publish = "/"

[[redirects]]
  from = "/loader.lua"
  to = "/.netlify/functions/loader"
  status = 200
  force = true

[[headers]]
  for = "/loader.lua"
  [headers.values]
    Content-Security-Policy = "default-src 'none'"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
